{
 "title": "Nakivo Backup & Replication",
 "time": { "from": "2024-04-25T10:52:12.356Z", "to": "2024-04-25T11:12:12.356Z" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(nakivo_backup_state,host)"
    }
   },
   {
    "name": "job_name",
    "label": "Nakivo Job Name",
    "query": {
     "query": "label_values(nakivo_backup_state,job_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Naviko Backups",
   "type": "stat",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nakivo_backup_state{host=~\"$host\",job_name=~\"$job_name\"}",
     "legendFormat": "{{object}}"
    }
   ]
  },
  {
   "title": "License status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nakivo_license_installed{host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "API Auth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nakivo_api_authentication_error{host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "API Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nakivo_api_error{host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Objects to backup",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nakivo_license_vmcount{host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Backup Duration",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nakivo_backup_duration{host=~\"$host\"}",
     "legendFormat": "{{object}}"
    }
   ]
  },
  {
   "title": "Backup Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nakivo_backup_size{host=~\"$host\"}",
     "legendFormat": "{{object}}"
    }
   ]
  }
 ]
}